# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"index_flow": "00_core.ipynb",
         "query_flow": "00_core.ipynb",
         "slugify": "01_loader.ipynb",
         "verify_image": "01_loader.ipynb",
         "get_image_files": "01_loader.ipynb",
         "device": "03_encoder.ipynb",
         "archive_loader": "01_loader.ipynb",
         "db_loader": "01_loader.ipynb",
         "treemap_loader": "01_loader.ipynb",
         "make_dataset": "02_crafter.ipynb",
         "pil_loader": "02_crafter.ipynb",
         "DatasetImagePaths": "02_crafter.ipynb",
         "clip_transform": "02_crafter.ipynb",
         "crafter": "02_crafter.ipynb",
         "preproc": "02_crafter.ipynb",
         "model": "03_encoder.ipynb",
         "image_encoder": "03_encoder.ipynb",
         "text_encoder": "03_encoder.ipynb",
         "image_query_encoder": "03_encoder.ipynb",
         "join_all": "04_indexer.ipynb",
         "build_treemap": "04_indexer.ipynb",
         "save_archives": "04_indexer.ipynb",
         "ranker": "05_ranker.ipynb",
         "nns_to_files": "05_ranker.ipynb",
         "top_bottom": "06_fileutils.ipynb",
         "copy_topn_images": "06_fileutils.ipynb",
         "app": "07_cli.ipynb",
         "recall": "07_cli.ipynb",
         "serve": "07_cli.ipynb",
         "__main__": "07_cli.ipynb",
         "get_image": "08_jupyter_gui.ipynb",
         "get_grid": "08_jupyter_gui.ipynb",
         "update_tabs": "08_jupyter_gui.ipynb",
         "appPage": "08_jupyter_gui.ipynb",
         "st_redirect": "09_streamlit_app.ipynb",
         "st_stdout": "09_streamlit_app.ipynb",
         "st_stderr": "09_streamlit_app.ipynb",
         "send_image_query": "09_streamlit_app.ipynb",
         "send_text_query": "09_streamlit_app.ipynb",
         "path": "09_streamlit_app.ipynb",
         "text_query": "09_streamlit_app.ipynb",
         "image_query": "09_streamlit_app.ipynb",
         "im_display_zone": "09_streamlit_app.ipynb",
         "logbox": "09_streamlit_app.ipynb",
         "sizes": "09_streamlit_app.ipynb"}

modules = ["core.py",
           "loader.py",
           "crafter.py",
           "encoder.py",
           "indexer.py",
           "ranker.py",
           "utils.py",
           "cli.py",
           "gui.py",
           "streamlit_app.py"]

doc_url = "https://deepfates.github.io/memery/"

git_url = "https://github.com/deepfates/memery/tree/main/"

def custom_doc_links(name): return None
