# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"MemeFolder": "02_folder.ipynb",
         "printi": "03_fileutils.ipynb",
         "top_bottom": "03_fileutils.ipynb",
         "copy_topn_images": "03_fileutils.ipynb"}

modules = ["core.py"]

doc_url = "https://deepfates.github.io/memery/"

git_url = "https://github.com/deepfates/memery/tree/main/"

def custom_doc_links(name): return None
