# AUTOGENERATED! DO NOT EDIT! File to edit: 05_ranker.ipynb (unless otherwise specified).

__all__ = ['ranker']

# Cell
def ranker(query_vec, treemap):
    nn_indexes = treemap.get_nns_by_vector(query_vec[0], treemap.get_n_items())
    return(nn_indexes)